### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by ghost** [abravodev/epubator#2]
![epubator](https://user-images.githubusercontent.com/36993664/39458520-036bd16c-4cfe-11e8-9b6a-bc03246ba517.jpg)

Hi,

I have studied your work and I think a new design will make you more visible. I designed for you, I hope you like it and you want to use it. If you want to reach me, you can look at the my profile. I can give you all the formats of the design free. If you want a change please specify.

**Comment by abravodev** [comment]
Wow, that's pretty nice. Though, original logo had an E in lowercase and it could be neat to have it in the new logo too. Perhaps, you could integrate it with the borders of the sheet of the file's logo. What do you think?

**Comment by ghost** [comment]
![logo-logotype](https://user-images.githubusercontent.com/36993664/39719628-74d5979a-5242-11e8-835b-d2d342f38ac3.jpg)

Thank u, 

It might be nice, I made an example, it would have been better on the right side. The decision is yours, we can make other changes if you want. The current state is plain and a logo that describes the app. What do you think?

**Comment by abravodev** [comment]
I agree with you, the second one is better. About the color, I'd rather a green similar to the one inside de app (something around #00897b should be fine)

For Android's notifications, we would also need a monochrome icon, I think it has to be white.

**Comment by ghost** [comment]
![epubator](https://user-images.githubusercontent.com/36993664/39877293-45b5f6b0-547e-11e8-9aec-8a52123c971b.png)

- The text is thickened.

- Colors changed.

- Black and White version added

If you approved, I can send you the files you need. It would be better if you told me which format and size you need. Please tell me if you want a change, thank you.

**Comment by abravodev** [comment]
I'm afraid I didn't explain properly the notification icon. In Android, we need an icon only in white (with transparent as the second color). It's explained better at 

- Notification icon: https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar
- Launcher icon: https://developer.android.com/guide/practices/ui_guidelines/icon_design#icon-sets
- Main Activity logo, as any image: https://developer.android.com/guide/practices/screens_support
Densities will be: ldpi, mdpi, hdpi, xhdpi, xxhdpi.
Current one is 480x480 and looks like this in the phone. 
<img src="https://user-images.githubusercontent.com/24463870/39930343-c0bab8e8-553a-11e8-86cd-44b338f6bb0e.png" width="200">

**Comment by ghost** [comment]
Hi, 

I have several options for the notification. Available in sizes from 18px to 48 px. I've added the logo from 48px to 512px. I added two options in the Logotype and added it to sizes from 48px to 512px.

Please write to me if there is any problem.

If the files are convenient I can send you a PR.

https://drive.google.com/open?id=1HgAUim3JHkMHMOCjE7wIhLzl6fV0-Zzs

**Comment by abravodev** [comment]
**Notification**
I like the v1 (the one with the simple name 18.png). Anyway, this is better to be checked in a real phone notification, so I'll have to test it before setting up my mind. However, I think you have to fix their dimensions, they don't match with their name (i.e.: 48.png shouldn't be 20x16).

**Logotype**
I like v1. We can keep it for the future or for other places.
Although, for the main view, I think is more suitable the v2 (the one with the icon above and the name below), but I'd prefer you to modify it. Instead of using that icon, use the other one (the one without the background). The icon with the square and background is better just for the launcher logo. And try to match the green color in the icon and the text. 
The one in the main view should be something like this
<img src="https://user-images.githubusercontent.com/24463870/39972374-17d6a982-570e-11e8-9a42-0a365f548fa9.png" width="200" />

I've checked the SVG files for the first Logotype version and they look incomplete, last letter is missing, when I open them on Chrome or Firefox. Rest of SVG files look OK. Might it be something I'm doing wrong?

BTW, I've tried to open the SVG files with Gimp but they look like mixed. I've opened other SVG files with Gimp in the past and didn't have problems.
<img src="https://user-images.githubusercontent.com/24463870/39972476-3b1e6bde-5711-11e8-9fce-d6b21723ed8a.png" width="200"/>

**Comment by ghost** [comment]
Hi,

I do not use Gimp, but I downloaded Gimp2. There was not a problem with the new files. You tried to make it black and white? I can also add black and white versions if desired.

* Logotype changed. The colors are arranged.

* Notification dimension edits were made.

https://drive.google.com/open?id=1HgAUim3JHkMHMOCjE7wIhLzl6fV0-Zzs

**Comment by abravodev** [comment]
I wasn't doing anything weird with it in Gimp. It might something related with my graphic card, though I tried another samples from Google and could open them.

I've already tried your images in the application and they look pretty good.
<img src="https://user-images.githubusercontent.com/24463870/40269643-9042b3a8-5b81-11e8-8938-8d1a4f7bd380.png" width="500">

**Comment by ghost** [comment]
I was very proud. Thank you. Is there any other file, format, size you want? Please say.

**Comment by abravodev** [comment]
In the app, we add the logo to the cover of the epub when the user chooses to. I'd like to use the main logotype without the app name at the bottom. Could you create those images too?

**Comment by ghost** [comment]
I update Google Drive and added it to the logo2 file. I hope that is correct. :)

**Comment by abravodev** [comment]
I had to crop the sides but it was fine. I've added you to the [Contributors section](https://github.com/abravodev/epubator#contributors) for the great help you've provided. The app looks completely different now thanks to you!
